<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.4.2" />
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
        <PackageReference Include="OpenTelemetry" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.7.1" PrivateAssets="All" />
        
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Frameset\Frameset.csproj" />
    </ItemGroup>

</Project>
